services:
  db:
    image: postgres:16
    container_name: fdms_db

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: frontdesk_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: fdms_api

    restart: unless-stopped

    ports:
      - "8000:8000"

    depends_on:
      - db

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/frontdesk_db

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000

    container_name: fdms_frontend

    restart: unless-stopped

    depends_on:
      - api

    ports:
      - "5173:80"

volumes:
  postgres_data: