"""add reminder email flags

Revision ID: 21f77d09bae6
Revises: 29de39570f93
Create Date: 2026-06-08 13:43:13.286859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f77d09bae6'
down_revision: Union[str, Sequence[str], None] = '29de39570f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('checkin_reminder_sent', sa.Boolean(), nullable=True))
    op.add_column('reservation', sa.Column('checkout_reminder_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'checkout_reminder_sent')
    op.drop_column('reservation', 'checkin_reminder_sent')
    # ### end Alembic commands ###
